### ISSUE TITLE
Add class-transformer decorators as well

### ISSUE THREAD

**Issue by iddan** [omar-dulaimi/prisma-class-validator-generator#10]
Hey, great job with this library!

## Problem

I would like to use it in Nest.js with the complementary class-transformer lib which requires more decorators

## Suggested solution

Add `@Type` etc.

## Alternatives

Create a different generator for my use case (might be better since I need `@nestjs/swagger` decorators as well.

**Comment by hmiiro** [comment]
@iddan did you succeed in creating the alternative? I would appreciate the swagger inclusion to this too.

**Comment by iddan** [comment]
Hey, the work on the REST API I worked on has paused. Recently I had a good experience using code generators for prisms nest graphql though.

**Comment by omar-dulaimi** [comment]
Hello!

Do you still need this?
I'm wondering if I should prioritize it next, and to learn more about how you're planning to add the decorators

**Comment by iddan** [comment]
Sorry, not it anymore

**Comment by omar-dulaimi** [comment]
Thanks for confirming
