### ISSUE TITLE
Don't use `IsDefined` as it conflicts with `skipMissingProperties`, making partial updates impossible

### ISSUE THREAD

**Issue by Morriz** [omar-dulaimi/prisma-class-validator-generator#9]
### Bug description

The output is now not usable for partial updates, as the validator requires props with `IsDefined()`, and `skipMissingProperties` does not work on them: https://github.com/typestack/class-validator#skipping-missing-properties

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by Morriz** [comment]
I created a feature request upstream: https://github.com/typestack/class-validator/issues/1726

**Comment by Morriz** [comment]
And published a fork in the mean time not using `IsDefined`: https://www.npmjs.com/package/prisma-class-validator-generator-partial

**Comment by omar-dulaimi** [comment]
Hey @Morriz
I apologize for not being as active here, I'm busy with job search and interviews that I don't get enough time to work on the many generators I have published so far. I hope you can understand that.

Also, you should have sent a PR instead of a whole fork and release lol.

**Comment by Morriz** [comment]
Got it. No PR as my fix is temporary and upstream should fix the problem.

**Comment by omar-dulaimi** [comment]
Closing for now, feel free to open in case something changes
